<div class='modal-custom'>
	<div class='modal-header'>
		<?php echo $this->translate('Team Settings')?>
	</div>
	<div class='modal-body' style='height:500px'>
		<ul class='nav nav-tabs'>
			<li id='teamset'><a href='/team/index/setting'><?php echo $this->translate('Basic Setting')?></a></li>
			<li id='membermanage'><a href='/team/index/member'><?php echo $this->translate('Member Manage')?></a></li>
			<li id='labelmanage'   class='active'><a href='/dailylog/label/index'><?php echo $this->translate('Category Manage')?></a></li>
			<li id='statistic'><a href='/dailylog/statistic/month'><?php echo $this->translate('Statistic')?></a></li>
		</ul>
		<div id='catmangediv'>
			<div class="input-prepend input-append">
				<div class="btn-group">
			    <button class="btn dropdown-toggle" data-toggle="dropdown">
			      Color
			      <span class="caret"></span>
			    </button>
				    <ul class="dropdown-menu" id='colorpicker'>
				    	<li><a id='clrf00'></a></li>
				    	<li><a id='clr0f0'></a></li>
				    	<li><a id='clr00f'></a></li>
				    	<li><a id='clr333'></a></li>
				    	<li><a id='clrff0'></a></li>
				    	<li><a id='clr0ff'></a></li>
				    	<li><a id='clrf0f'></a></li>
				   </ul>
			 	</div>
				
				<input type="text" id='label' name='label'/><button class='btn' id='addlabel'><?php echo $this->translate('Add')?></button>
			</div>
			
			<table id='labellist' class='table table-striped'>
					
			</table>
		</div>
	</div>
	<div class='modal-footer'></div>
</div>
