<div style='float:right;margin-top:-400px;margin-right:100px'>
	<ul class='unstyled'>
		<li><a style='color:#fff'  href='/user/index/index?lang=en_US'>English</a></li>
		<li><a style='color:#fff' href='/user/index/index?lang=zh_CN'>中文</a></li>
		<li><a style='color:#fff' href='/user/index/index?lang=ja_JP'>日本语</a></li>
	</ul>
</div>
<div class='row-fluid'>
 	<?php if(isset($error)):?>
	<div class='btn btn-warning'><strong><?php echo $error?></strong></div><br/>
	<?php endif;?>
	<form action='/user/index/login' method='post' class='valign'>
		<div class="row-fluid">
			<input type='text' id='email' class='span2' name='email' placeholder=<?php echo $this->translate('Email')?>>
		</div>
		<div class='row-fluid'>
			<input type='password' id='password' class='span2' name='password' placeholder=<?php echo $this->translate('Password')?>>
		</div>
		<div class='row-fluid'>
			<input type='submit' id='submit' class='btn span2 btn-info btn-default' value=<?php echo $this->translate('Login')?>>
		</div>
	</form>
	<a href='/user/index/forgetpw'><?php echo $this->translate('Forget password')?></a>
	<a href='/user/index/register'><?php echo $this->translate('Register')?></a>
</div>