<div class='row' >
<form action='/user/index/register' method='post' class='white-bg valign' style='width:500px;position:relative;left:50%;margin-left:-250px'>
	<?php if(isset($error)):?>
	<div class='btn btn-warning'><strong><?php echo $this->translate('Account or Password is wrong') ?></strong></div><br/>
	
	<?php endif;?>
	<div class="row-fluid">
		<input type='text' id='email' name='email' placeholder=<?php echo $this->translate('Email')?>>
	</div>
	<div class='row-fluid'>
		<input type="text" id='teamname' name='teamname' placeholder=<?php echo $this->translate('Team Name')?>>
	</div>
	<div class='row-fluid'>
		<input type='password' id='password' name='password' placeholder=<?php echo $this->translate('Password')?>>
	</div>
	<div class='row-fluid'>
		<input type='text' id='username' name='username' placeholder=<?php echo $this->translate('Username')?>>
	</div>
	<div class='row-fluid'>
		<input type='submit' id='submit' class='btn btn-info  btn-default' value=<?php echo $this->translate('Register Team')?>>
	</div>
	<div>&nbsp;</div>
</form>
</div>

